package colabbs.net;

/**
 * This class was generated by a SmartGuide.
 * 
 */
import java.util.*;
import java.text.*;
import java.io.*;
import java.net.*;

import colabbs.*;
import colabbs.record.*;
import colabbs.UTILS.*;
import colabbs.DATA.BOARD.*;

public final class ColaINND extends NetworkServer
{
	private char appendChar='A'; //for creat file and refresh board time....
	private long theTime=-1;
	
	private PrintWriter clientOutput = null;
/**
 * ColaMail constructor comment.
 */
public ColaINND() 
{
	super();
}
/**
 * This method was writen by yhwu.
 * @return java.lang.String
 * @param thePath java.lang.String
 */
private String createFile(String thePath)
{
	String SaveFileName;
	// search the file name for create, just for safe....
	appendChar='A'-1; //for creat file and refresh board time....
	theTime=-1;
	
	theTime=((new Date()).getTime()/1000);
	do
	{
		appendChar++;
		SaveFileName="M."+theTime+"."+appendChar;
	}while((new File(thePath,SaveFileName)).exists());
	return SaveFileName;
}
public void doService()
		throws IOException
{
	InetAddress theAddr=clientSocket.getInetAddress();
	boolean found=false;
	
	clientOutput = new PrintWriter(new BufferedOutputStream(clientSocket.getOutputStream()),false);
	
	synchronized(Consts.NewsNode)
	{
		RecordHandler rh=null;
		NewsNodeType nnt=new NewsNodeType();

		found=false;
		
		try
		{
			rh=new RecordHandler(ColaServer.INI.BBSHome,Consts.NewsNode,true);
			while(rh.nextElement(nnt))
				if(theAddr.equals(InetAddress.getByName(nnt.getAddress())))
					found=true;
		}
		finally
		{
			if(rh!=null)
			{
				rh.close();
				rh=null;
			}
		}
	}
	if(!found)
	{
		clientOutput.print("502 You are not in my access file. ("+theAddr+")\r\n");
		clientOutput.flush();
		ColaServer.BBSlog.Write("Invalid access from "+theAddr);
		return;
	}
	clientOutput.print("200 "+InetAddress.getLocalHost().getHostName()+" ColaINND 1.0.0 ("+theAddr+").\r\n");
	clientOutput.flush();
	
	byte readbuf=0;
	int i;
	StringBuffer Cmd=new StringBuffer(512);
	String Command,Arg=null;
	StringTokenizer st;

ServiceLoop:	
	while((i=is.read())!=-1)
	{
		RandomAccessFile theFile=null;
		
		switch(i)
		{
			case 10:
				break;
			case 13:
				Command=Cmd.toString();
				ColaServer.BBSlog.Write("ColaINND : "+Command);
				Cmd.setLength(0);
				
				if(Command.length()>=5&&Command.substring(0,5).equalsIgnoreCase("ihave"))
				{
					String path=ColaServer.INI.IBBSName+"!";
					String title=new String("");
					String group=new String("");
					String from=new String("");
					String date=new String("");
					String site=new String("");
					String mid=new String("");
					DataInputStream dis=null;
					if(Command.indexOf(' ')==-1)
					{
						clientOutput.print("435 Usage: ihave mid\r\n");
						clientOutput.flush();
						break;
					}
					Arg=Command.substring(6);
					if(Arg.length()<2||Arg.indexOf('<')==-1||Arg.indexOf('>')==-1||Arg.indexOf('@')==-1)
						break;
					mid=Arg.substring(Arg.indexOf('<')+1,Arg.indexOf('>'));
					
					clientOutput.print("335 Enter article, end with \".\" on a line by itself\r\n");
					clientOutput.flush();
// Post the article.....
					{
						String clientbuf=null;
						StringBuffer clientdata=new StringBuffer(512);
						int r=0;

						//receive the header....
						while(true)
						{
HeadLoop:
							while((r=is.read())!=-1)
							{
								switch(r)
								{
									case 10:
										break;
									case 13:
										clientbuf=clientdata.toString();
										clientdata.setLength(0);
										break HeadLoop;
									default:
										clientdata.append((char)r);
										break;
								}	
							}
							if(r==-1)
								return;
							if(clientbuf.length()<=0)
								break;
							System.out.println(clientbuf);
							if(clientbuf.length()>=6&&clientbuf.substring(0,6).equalsIgnoreCase("Path: "))
								path=ColaServer.INI.IBBSName+"!"+clientbuf.substring(6);
							if(clientbuf.length()>=6&&clientbuf.substring(0,6).equalsIgnoreCase("From: "))
								from=clientbuf.substring(6);
							if(clientbuf.length()>=12&&clientbuf.substring(0,12).equalsIgnoreCase("Newsgroups: "))
								group=clientbuf.substring(12);
							if(clientbuf.length()>=9&&clientbuf.substring(0,9).equalsIgnoreCase("Subject: "))
								title=clientbuf.substring(9);
							if(clientbuf.length()>=6&&clientbuf.substring(0,6).equalsIgnoreCase("Date: "))
								date=clientbuf.substring(6)+" ";
							if(clientbuf.length()>=14&&clientbuf.substring(0,14).equalsIgnoreCase("Organization: "))
								site=clientbuf.substring(14);
						}	
					}
					//receive the body....
					BoardItem found2=null;
					synchronized(Consts.NewsFeed)
					{
						RecordHandler rh=null;
						NewsFeedType nft=new NewsFeedType();

						found2=null;
		
						try
						{
							rh=new RecordHandler(ColaServer.INI.BBSHome,Consts.NewsFeed,true);
						SearchBoardLoop:
							while(rh.nextElement(nft))
								if(nft.getNewsGroup().equals(group))
								{
									found2 = ColaServer.BList.get(nft.getBoardName());
									break SearchBoardLoop;
/*									//search the board item....
									LinkType Base=ColaServer.BBSBoards.Boards.GetBase();
									LinkType ptr=Base;
									BoardItem BoardBuf=null;

									if(Base==null)
										break SearchBoardLoop;

									do
									{
										BoardBuf=(BoardItem)ptr.obj;
										if(BoardBuf.Name.equalsIgnoreCase(nft.getBoardName()))
										{
											found2=BoardBuf;
											break SearchBoardLoop;
										}
										ptr=ptr.next;
									}while(ptr!=Base);*/
								}
						}
						finally
						{
							if(rh!=null)
							{
								rh.close();
								rh=null;
							}
						}
					}
					if(found2==null)
					{
						int last2=0,last1=0;
						
						while(true)
						{
							int buf=is.read();
							if(buf==-1)
								break;
							if(((last2==(int)'\r')||(last2==(int)'\n'))&&(last1==(int)'.')&&(buf!=(int)'.'))
								break;
							last2=last1;
							last1=buf;
						}	
					}
					else
					{
						try
						{
							int last2=0,last1=0;
							ParsePosition pos = new ParsePosition(0);
							String filename=createFile(ColaServer.INI.BBSHome+"boards"+File.separator+found2.Name+File.separator);
						
							RecordHandler.append(found2,new PostType(filename,from,title,(byte)'L'),ColaServer.INI.BBSHome+"boards"+File.separator+found2.Name+File.separator,Consts.DotDir);
						
							theFile=new RandomAccessFile(ColaServer.INI.BBSHome+"boards"+File.separator+found2.Name+File.separator+filename,"rw");
							theFile.writeBytes(Prompt.Msgs[46]+STRING.Cut(from,46)+Prompt.Msgs[183]+STRING.Cut(found2.Name,20)+"[m\r\n");
							theFile.writeBytes(Prompt.Msgs[65]+STRING.Cut(title,73)+"[m\r\n");
							theFile.writeBytes(Prompt.Msgs[271]+STRING.Cut(site+" ("+ColaServer.SysDATE.DateFormatter2.format(NNTPClient.formatter.parse(date,pos))+")",73)+"[m\r\n");
							theFile.writeBytes(Prompt.Msgs[237]);
							theFile.writeBytes("\r\n");
							
							while(true)
							{
								int buf=is.read();
								if(buf==-1)
									break;
								if(((last2==(int)'\r')||(last2==(int)'\n'))&&(last1==(int)'.')&&(buf!=(int)'.'))
									break;
								else if(last1=='.')
									theFile.writeByte('.');
								last2=last1;
								last1=buf;
								if(buf!='.')
									theFile.writeByte(buf);
							}	
						}
						catch(Exception e)
						{
							e.printStackTrace();
						}
						finally
						{
							if(theFile!=null)
							{
								theFile.close();
								theFile=null;
							}
						}
					}
					if(theTime!=-1)
					{
						found2.filetime=theTime*1000L+(appendChar-'A');
						theTime=-1;
					}
					System.out.println(from+" post article "+title+" to "+group);
					clientOutput.print("235 Message accepted for delivery\r\n");
					clientOutput.flush();
				}	
				else if(Command.equalsIgnoreCase("noop"))
				{
					clientOutput.print("250 OK\r\n");
					clientOutput.flush();
				}	
				else if(Command.equalsIgnoreCase("help"))
				{
					clientOutput.print("214-This is ColaINND version 1.0.0\r\n");
					clientOutput.print("214-Topics:\r\n");
					clientOutput.print("214-    HELP    IHAVE    NOOP   QUIT\r\n");
					clientOutput.print("214-To report bugs in the implementation send email to\r\n");
					clientOutput.print("214-    is85003@cis.nctu.edu.tw.\r\n");
					clientOutput.print("214-For local information send email to SYSOP at your site.\r\n");
					clientOutput.print("214 End of HELP info\r\n");
					clientOutput.flush();
				}	
				else if(Command.equalsIgnoreCase("quit"))
				{
					clientOutput.print("221 "+InetAddress.getLocalHost().getHostName()+" closing connection\r\n");
					clientOutput.flush();
					break ServiceLoop;
				}
				else	
				{
					clientOutput.print("500 Command unrecognized: "+Command+"\r\n");
					clientOutput.flush();
				}	
				break;
			default:
				if(Cmd.length()<512)
					Cmd.append((char)i);
				break;
		}	
	}	
}
}